//
//  FindtheDifference.swift
//  LeetCode
//
//  Created by You Tu on 2017/9/14.
//  Copyright © 2017年 You Tu. All rights reserved.
//

/*
 Given two strings s and t which consist of only lowercase letters.
 
 String t is generated by random shuffling string s and then add one more letter at a random position.
 
 Find the letter that was added in t.
 
 Example:
 
 Input:
 s = "abcd"
 t = "abcde"
 
 Output:
 e
 
 Explanation:
 'e' is the letter that was added.
 */

import Cocoa

class FindtheDifference: NSObject {
    func findTheDifference(_ s: String, _ t: String) -> Character {
        
        var record = Array.init(repeating: 0, count: 26)
        for ch in t.characters {
            record[characterValue(ch) - 97] += 1
        }
        
        for ch in s.characters {
            record[characterValue(ch) - 97] -= 1
        }
        
        for (index, val) in record.enumerated() {
            if val > 0 {
                return Character(UnicodeScalar(97 + index)!)
            }
        }
        
        return Character("0")
    }
    
    func characterValue(_ a: Character) -> Int {
        let charaterString = String(a)
        let scalars = charaterString.unicodeScalars
        let value = scalars[scalars.startIndex].value
        return Int(value)
    }
}
